DROP TABLE IF EXISTS chonks;

CREATE TABLE chonks (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  weight BIGINT NOT NULL,
  description TEXT NOT NULL,
  image_url TEXT NOT NULL
)

